package ui;

import dao.EmployeeDAO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;

public class EmployeeDepartmentHistoryFrame extends JFrame {

    private final EmployeeDAO employeeDAO = new EmployeeDAO();
    private final int employeeId;

    private DefaultTableModel model = new DefaultTableModel(
            new Object[]{"History ID", "Department", "Start Date", "End Date"}, 0
    ) {
        @Override public boolean isCellEditable(int r, int c) { return false; }
    };

    private JTable table = new JTable(model);

    private JButton btnRefresh = new JButton("Refresh");
    private JButton btnClose = new JButton("Close");

    public EmployeeDepartmentHistoryFrame(int employeeId) {
        super("Department History (Employee ID: " + employeeId + ")");
        this.employeeId = employeeId;

        initUI();
        loadHistory();
    }

    private void initUI() {
        setSize(720, 420);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout(10, 10));

        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        add(new JScrollPane(table), BorderLayout.CENTER);

        JPanel btns = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        btns.add(btnRefresh);
        btns.add(btnClose);

        btnRefresh.addActionListener(e -> loadHistory());
        btnClose.addActionListener(e -> dispose());

        add(btns, BorderLayout.SOUTH);
    }

    private void loadHistory() {
        try {
            model.setRowCount(0);
            List<Object[]> rows = employeeDAO.getDepartmentHistoryRows(employeeId);

            for (Object[] r : rows) {
                Date end = (Date) r[3];
                Object endDisplay = (end == null) ? "Current" : end;
                model.addRow(new Object[]{ r[0], r[1], r[2], endDisplay });
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Failed to load department history:\n" + ex.getMessage(),
                    "DB Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
